#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer --file_ignore="./_site/admin/index.html" ./_site --disable-external --empty-alt-ignore --check-favicon --check-opengraph
